jacob_prompt = """I will provide a series of data for you to remember. Subsequently, I will ask you some
questions to test your performance! Here are some descriptions for you to memorize.

{text}

I’m trying to understand the behavior of different language models. The above are some descriptions of model outputs, and I'd like to cluster them into different axes of variation. Using these specific examples, are there any general patterns, clusters, or variations you notice in the descriptions? Try to give patterns that are specific enough that someone could reliably produce new examples that fit the rule, and that they could understand what it means to be higher or lower on that specific axis. Please try to give as
many general patterns as possible. Please focus on patterns that are important for understanding the behavior of a language model, as these will later be used to help debug an important system. Please explain clearly why the pattern would be important for understanding the behavior of such a system. Please summarize as many as you can and stick to the examples."""

jacob_prompt_pt2 = """Thank you. Now I would like you to use these axes to categorize the specific examples I gave you. To start with, let's consider the first axis you chose:
{cluster}

I want you to consider each of the specific descriptions from before, and determine whether they are relevant to this axis. If they are, say how they score along this axis on a scale of -5 to 5, where -5 means they are strongly towards the low end of the axis, and 5 means they are strongly towards the high end. Provide your output as a list of descriptions followed by the score, each on one line, such as
{{first description}}: {{score from -5 to 5}}
{{second description}}: {{score from -5 to 5}}
Include only the descriptions that are relevant to the axis. As a reminder, here are the descriptions from before:

{text}
"""

systems_prompt = "Given a dataset of text outputs from two different large language models (LLMs), your task is to analyze and summarize the data based on specific characteristics. The goal is to identify and cluster similar behaviors or traits within the outputs, summarizing these into a concise list of commonly observed behaviors for each model. This analysis will help in understanding the general behaviors of these models for auditing, error discovery, and comparison purposes.\n\n1. Clustering: Identify and group text outputs that share common themes, behaviors, or characteristics. Use the clustering to reveal insights about the models' tendencies in generating text.\n\n2. Summarization: For each cluster identified, provide a summary that encapsulates the key behaviors or traits observed. This should offer a clear, concise overview of the commonalities within the cluster.\n\n3. Comparative Analysis: Compare the summarized behaviors between the two LLMs. Highlight differences and similarities in their output characteristics, providing insights into their unique or shared behaviors.\n\n4. Recommendations: Based on the analysis, suggest potential areas for model improvement or further investigation.\n\nYour analysis should take into account the context that these text outputs are generated by LLMs, focusing on the qualitative aspects that distinguish one model from another. Provide your findings in a structured and easily understandable format."