project: VibeCheck-Benchmark
wandb: False # Set to True to log to Weights and Biases
num_samples: False
dummy_eval: False
oz: False
group_column: False
test: False
save_dir: pipeline_results
data_path: data/benchmark/arena_data.csv
# data_path: data/benchmark/arena_friendly_and_cold_smaller.csv
k: 3
batch_size: 50
num_axes_generated: 5
num_eval: 10
embedding_model: text-embedding-3-small
seed: 42
cluster_method: hierarchical
ranker: MuliRubricRankerJury
# sampler: ClusterSampler
sampler: Sampler
reducer: AxisReducer
proposer: LLMProposerMultiModel
num_topic_clusters: 5
heldout_percentage: 0.75
proposer_batch_size: 5
judges: [claude-3-haiku-20240307, llama-3-8b, llama-3-70b]
models: ['base', 'funny']
# models: ['base', 'friendly-and-personable', 'cold-and-factual', 'storyteller', 'organized', 'safety-concious', 'conspiracy-theorist', 'funny', 'imaginative', 'anotagonistic']
# models: [A, B]
eval_only: False
axes: False
