data_path: data/all.csv
output_name: False
model_a_column: human_answers
model_b_column: chatgpt_answers
k: 3
batch_size: 50
num_eval: 3
num_axes_generated: 10
embedding_model: text-embedding-3-small
seed: 42
cluster_method: hierarchical
ranker: LLMOnlyRanker
proposer_batch_size: 5
proposer_only: False
oz: False
dummy_eval: False
proposer: LLMProposerMultiModel
reducer: AxisReducer
sampler: ClusterSampler
num_topic_clusters: 5
test: False
save_dir: pipeline_results
early_stopping: True
topic_based_rubric_example: False
early_stopping_threshold: 0.1