project: VibeCheck-Benchmark
wandb: False # Set to True to log to Weights and Biases
num_samples: 50
dummy_eval: False
oz: False
group_column: False
test: False
save_dir: pipeline_results
data_path: data/benchmark/train.csv
test_data_path: data/benchmark/test.csv
# data_path: data/benchmark/arena_friendly_and_cold_smaller.csv
k: 3
batch_size: 50
num_axes_generated: 10
num_eval: 25
embedding_model: text-embedding-3-small
seed: 42
cluster_method: hierarchical
ranker: MuliRubricRankerJury
# sampler: ClusterSampler
sampler: Sampler
reducer: AxisReducer
proposer: LLMProposerMultiModel
num_topic_clusters: 5
heldout_percentage: 0.75
proposer_batch_size: 1
judges: [llama-3-8b, llama-3-70b]
models: ['friendly-and-personable', 'cold-and-factual', 'safety-concious', 'conspiracy-theorist', 'funny', 'imaginative', 'anotagonistic']
# ['friendly and personable', 'professional', 'casual', 'cold-and-factual', 'storyteller', 'organized', 'safety-concious', 'conspiracy-theorist', 'funny', 'imaginative', 'anotagonistic']
eval_only: False
axes: False

new_sample: True

# models
rubric_generation_model: "gpt-4o"
proposer_model: "claude-3-opus-20240229"
