project: LLMEval
wandb: true  # whether to log to wandb
seed: 1  # random seed

data:
  root: ./data
  name: all_old_format  # name of dataset
  group1: human  # name of group 1
  group2: chatgpt  # name of group 2
  purity: 1.0  # how much of each concept is in each group (1.0 means perfect seperation, 0.5 means perfect mix)
  # subset: palm-2 # if you want to use a subset of the dataset, set this to name of the desired subset value

proposer:  # LLM Proposer
  method: DualSidedLLMProposer  # how to propose hypotheses
  model: gpt-4  # model used in method
  num_rounds: 100 # number of rounds to propose
  num_samples: 1  # number of samples per group to use
  sampling_method: random  # how to sample
  num_hypotheses: 3  # number of hypotheses to generate per round
  prompt: LLM_ONLY_PROMPT_OZ
  oz_axes: ["Tone", "Format", "Level of Detail", "Ability to answer", "Approach", "Creativity", "Fluency and crammatical correctness", "Specificity and detail", "Adherence to prompt"]

ranker:  # LLM Ranker 
  method: DualClusterRanker

evaluator:
  method: NullEvaluator  # how to evaluate hypotheses
