project: LLMEval
wandb: true  # whether to log to wandb
seed: 1  # random seed

data:
  root: ./data
  name: gpt_claude_writing  # name of dataset
  group2: "gpt-4"  # name of group 1
  group1: "claude-v1"  # name of group 2
  purity: 1.0  # how much of each concept is in each group (1.0 means perfect seperation, 0.5 means perfect mix)
  # subset: palm-2 # if you want to use a subset of the dataset, set this to name of the desired subset value

proposer:  # LLM Proposer
  method: LLMPairwiseProposerWithQuestion  # how to propose hypotheses
  model: gpt-4  # model used in method
  num_rounds: 10  # number of rounds to propose
  num_samples: 1  # number of samples per group to use
  sampling_method: random  # how to sample
  num_hypotheses: 10  # number of hypotheses to generate per round
  prompt: LLM_ONLY_PROMPT  # prompt to use

ranker:  # LLM Ranker
  method: NullRanker  # how to rank hypotheses
  # model: gpt-3.5-turbo # model used in method

evaluator:
  method: NullEvaluator  # how to evaluate hypotheses
